[project]
name = "boidy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pygame>=2.6.1",
    "pytest>=8.3.5",
    "tqdm>=4.67.1",
    "types-tqdm>=4.67.0.20250516",
]
